<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-28T22:21:39 EET" name="Default suite" finished-at="2024-08-28T22:21:50 EET" duration-ms="10867">
    <groups>
    </groups>
    <test started-at="2024-08-28T22:21:39 EET" name="Default test" finished-at="2024-08-28T22:21:50 EET" duration-ms="10867">
      <class name="databasetesting.DataTest">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:databasetesting.DataTest@62679465]" started-at="2024-08-28T22:21:39 EET" name="mySetup" finished-at="2024-08-28T22:21:40 EET" duration-ms="431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="AddToThedataBase()[pri:1, instance:databasetesting.DataTest@62679465]" started-at="2024-08-28T22:21:40 EET" name="AddToThedataBase" finished-at="2024-08-28T22:21:40 EET" duration-ms="416" status="FAIL">
          <exception class="java.sql.SQLIntegrityConstraintViolationException">
            <message>
              <![CDATA[Duplicate entry '505' for key 'customers.PRIMARY']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '505' for key 'customers.PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1537)
at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2384)
at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1410)
at databasetesting.DataTest.AddToThedataBase(DataTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLIntegrityConstraintViolationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddToThedataBase -->
        <test-method signature="updateData()[pri:2, instance:databasetesting.DataTest@62679465]" started-at="2024-08-28T22:21:40 EET" name="updateData" finished-at="2024-08-28T22:21:40 EET" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateData -->
        <test-method signature="myFirstTestGetData()[pri:3, instance:databasetesting.DataTest@62679465]" started-at="2024-08-28T22:21:40 EET" name="myFirstTestGetData" finished-at="2024-08-28T22:21:50 EET" duration-ms="9464" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTestGetData -->
        <test-method signature="DeleteData()[pri:4, instance:databasetesting.DataTest@62679465]" started-at="2024-08-28T22:21:50 EET" name="DeleteData" finished-at="2024-08-28T22:21:50 EET" duration-ms="492" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteData -->
      </class> <!-- databasetesting.DataTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
